### ISSUE TITLE
Long fasta headers raise errors

### ISSUE THREAD

**Issue by bioinformagica** [gbouras13/phrokka#89]
* phrokka version: 1.0.1
* Python version: Python 3.9.13 (build deps with conda)
* Operating System: Debian GNU/Linux 9 (stretch)

Dear developers, first of all, thank you very much for making this tool, it will be very useful for annotating my phages !
 
I was trying to run phrokka with one of my assemblies and the program threw an error.

```bash
Running hmmsuite
data file: teste_ph-f/hhsuite_target_dir/hhsuite_tsv_file.ffdata
index file: teste_ph-f/hhsuite_target_dir/hhsuite_tsv_file.ffindex
fasta file: teste_ph-f/phanotate_aas.fasta
- 21:00:16.274 INFO: Searching 38880 column state sequences.

- 21:00:16.357 INFO: Thread 0   S34#1#2210b5d2-d153-4961-bdbc-a4

- 21:00:16.374 ERROR: Error in /opt/conda/conda-bld/hhsuite_1645696999782/work/src/hhfunc.cpp:83: ReadQueryFile:

- 21:00:16.374 ERROR:   unrecognized input file format in 'S34#1#2210b5d2-d153-4961-bdbc-a4'

- 21:00:16.374 ERROR:   line = 0f0688b033delimiter0

Processing mmseqs output
Processing hhsuite output
Traceback (most recent call last):
  File "/home/hugoa/repos/phrokka/bin/phrokka.py", line 36, in <module>
    phan_mmseq_merge_df = post_processing.process_results(DBDIR, out_dir)
  File "/home/hugoa/repos/phrokka/bin/modules/post_processing.py", line 75, in process_results
    tophits_hmm__df[['spl','ind']] = tophits_hmm__df['gene_hmm'].str.split('delimiter',expand=True)
  File "/home/hugoa/miniconda3/envs/ph_dev/lib/python3.9/site-packages/pandas/core/frame.py", line 3643, in __setitem__
    self._setitem_array(key, value)
  File "/home/hugoa/miniconda3/envs/ph_dev/lib/python3.9/site-packages/pandas/core/frame.py", line 3685, in _setitem_array
    check_key_length(self.columns, key, value)
  File "/home/hugoa/miniconda3/envs/ph_dev/lib/python3.9/site-packages/pandas/core/indexers/utils.py", line 428, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
```
After some investigation, I found that maybe the problem is with the file "test/hhsuite_target_dir/hhsuite_tsv_file.ffdata" and the program used to build it.
It looks like when a header is long like mine:

```bash
S34#1#2210b5d2-d153-4961-bdbc-a40f0688b033
```
The pipeline breaks on creating the hh index and reading the resulting table in pandas.
I found the header size to be an issue because I tried editing my fasta header, removing special characters like '#_-', but the error still happened.
The only thing that worked was shortening the string to:

```bash
S3412210b5d2d
``` 
After editing the header the program runs until the end, but it would be nice not to have to edit the header.

Best regards !

**Comment by gbouras13** [comment]
Hi bioinfomagica,

Thanks for using and testing phrokka - and for your pull request also.

I have done some digging and it seems as though this is a known issue with hhbilts.

https://github.com/soedinglab/hh-suite/issues/263 

Accordingly, I will write a module that trims long fasta headers automatically.

George

**Comment by gbouras13** [comment]
I have fixed this - let me know how you go.
