### ISSUE TITLE
add --prefix

### ISSUE THREAD

**Issue by gbouras13** [gbouras13/phrokka#95]
Add --prefix flag to allow users to name the output files

**Comment by iferres** [comment]
Hi @gbouras13 , just a related suggestion here. 

Would be possible to apply the `--prefix` value over all the output files? For instance, over `phanotate.{ffn,faa}`, `prodigal-gv.{ffn,faa}`,  etc. The use case is when integrating pharokka into a workflow is much easier to predict the output filenames to stage them as processes outputs. If `--prefix example1234`, I would name those files as `example1234.ffn` and `example1234.faa`. Also for the `terL.{ffn,faa}`, `top_hits_card.tsv`, `top_hits_vfdb.tsv`, and `trnascan_out.gff`, I would apply the prefix as `example123_terL.ffn`, ..., but just for aesthetics reasons haha 😅 . 

May be it would break compatibility with already implemented pipelines if the behavior of the parameter changes, so not sure if it is a good idea right now. 

Another option would be to add another flag, such as `--prefix_all` or something like that, but I know it makes the code more complicated. So, I leave the suggestion here and you see haha. 

Eager to trying out phold, thanky very much for all this software!
